export function renderInstagramReviewPage() {
  return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Afiliados Pro | Integração Instagram</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#eef2ff;background:#070b18}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at top,#312e81,#070b18 58%)}main{max-width:920px;margin:auto;padding:32px 18px 60px}.brand{display:flex;align-items:center;gap:12px;margin-bottom:24px}.logo{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(135deg,#833ab4,#fd1d1d,#fcb045);font-weight:900;color:white}.card{background:rgba(15,23,42,.94);border:1px solid #334155;border-radius:20px;padding:24px;margin:16px 0;box-shadow:0 20px 50px #0005}h1{margin:0;font-size:28px}h2{font-size:20px}p{color:#cbd5e1;line-height:1.55}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{display:block;font-weight:700;margin:12px 0 7px}input,select,textarea{width:100%;padding:12px 14px;border-radius:12px;border:1px solid #475569;background:#0b1224;color:#fff;font:inherit}textarea{min-height:100px;resize:vertical}button{border:0;border-radius:12px;padding:12px 16px;font-weight:800;font-size:15px;cursor:pointer}.primary{background:linear-gradient(90deg,#833ab4,#fd1d1d,#fcb045);color:white}.secondary{background:#e2e8f0;color:#111827}.ghost{background:#273449;color:#fff}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.status{border-radius:12px;padding:12px 14px;background:#111c31;color:#dbeafe}.ok{border-left:4px solid #22c55e}.warn{border-left:4px solid #f59e0b}.error{border-left:4px solid #ef4444}.hidden{display:none}.consent{display:flex;gap:10px;align-items:flex-start;margin-top:16px}.consent input{width:auto;margin-top:4px}.profile{margin-top:12px;padding:14px;border:1px solid #334155;border-radius:12px;background:#0b1224}.note{font-size:13px;color:#94a3b8}@media(max-width:650px){.grid{grid-template-columns:1fr}.card{padding:18px}}
</style></head><body><main>
<div class="brand"><div class="logo">AP</div><div><h1>Afiliados Pro</h1><p style="margin:2px 0">Integração oficial com Instagram</p></div></div>
<section id="loginCard" class="card"><h2>Entrar</h2><p>Use sua conta Afiliados Pro para gerenciar somente suas próprias campanhas e conexões.</p>
<form id="loginForm"><label for="email">E-mail</label><input id="email" type="email" autocomplete="username" required><label for="password">Senha</label><input id="password" type="password" autocomplete="current-password" required><div class="actions"><button class="primary" type="submit">Entrar com segurança</button></div></form><div id="loginStatus"></div></section>
<section id="appCard" class="card hidden"><h2>Conta profissional do Instagram</h2><div id="connectionStatus" class="status warn">Verificando conexão...</div><div id="profileInfo" class="profile hidden"></div><div class="actions"><button id="connectButton" class="secondary" type="button">Conectar Instagram</button><button id="refreshButton" class="ghost" type="button">Atualizar status</button><button id="logoutButton" class="ghost" type="button">Sair</button></div><p class="note">A conexão usa o Login do Instagram. O Afiliados Pro não solicita nem armazena sua senha do Instagram.</p></section>
<section id="publishCard" class="card hidden"><h2>Publicar Reel no Instagram</h2><p>Selecione um vídeo pronto de uma campanha e revise a legenda antes de autorizar a publicação.</p>
<label for="videoOption">Campanha e vídeo</label><select id="videoOption"></select>
<div class="grid"><div><label for="caption">Legenda</label><textarea id="caption" maxlength="1800">Oferta selecionada pelo Afiliados Pro. Confira esta oportunidade.</textarea></div><div><label for="hashtags">Hashtags</label><input id="hashtags" value="oferta, afiliadospro"><label for="cta">Chamada para ação</label><input id="cta" value="Confira a oferta no link"></div></div>
<label class="consent"><input id="consent" type="checkbox"><span>Eu revisei este conteúdo e autorizo o Afiliados Pro a publicar este Reel na minha conta profissional do Instagram.</span></label>
<div class="actions"><button id="publishButton" class="primary" type="button">Publicar Reel no Instagram</button></div><div id="operationStatus"></div></section>
</main><script>
const tokenKey='afiliadosProInstagramReviewToken';const $=(id)=>document.getElementById(id);let token=sessionStorage.getItem(tokenKey)||'';
function auth(){return {'Authorization':'Bearer '+token,'Content-Type':'application/json'}}
function message(target,text,type='warn'){target.className='status '+type;target.textContent=String(text)}
async function jsonRequest(url,options={}){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Não foi possível concluir a operação.');return data}
async function loadOptions(){const data=await jsonRequest('/distribution/instagram/options',{headers:auth()});$('appCard').classList.remove('hidden');if(data.connected){const name=data.connection.destinationName;message($('connectionStatus'),'Instagram conectado com sucesso.','ok');$('profileInfo').classList.remove('hidden');$('profileInfo').textContent='Perfil profissional conectado: '+(name.startsWith('@')?name:'@'+name);$('publishCard').classList.remove('hidden')}else{message($('connectionStatus'),'Nenhuma conta profissional do Instagram conectada.','warn');$('profileInfo').classList.add('hidden');$('publishCard').classList.add('hidden')}
const select=$('videoOption');select.innerHTML='';data.options.forEach(item=>{const option=document.createElement('option');option.value=JSON.stringify(item);option.textContent=item.campaignName+' — vídeo pronto';select.appendChild(option)});if(!data.options.length){const option=document.createElement('option');option.textContent='Nenhum vídeo pronto encontrado';option.value='';select.appendChild(option)}}
async function restore(){if(!token)return;$('loginCard').classList.add('hidden');try{await loadOptions()}catch(error){token='';sessionStorage.removeItem(tokenKey);$('loginCard').classList.remove('hidden');message($('loginStatus'),error.message,'error')}}
$('loginForm').addEventListener('submit',async(event)=>{event.preventDefault();try{const data=await jsonRequest('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});token=data.token;sessionStorage.setItem(tokenKey,token);$('password').value='';$('loginCard').classList.add('hidden');await loadOptions()}catch(error){message($('loginStatus'),error.message,'error')}});
$('connectButton').addEventListener('click',async()=>{try{const data=await jsonRequest('/channel/instagram/oauth/start',{headers:auth()});window.open(data.authorizationUrl,'instagramOAuth','width=760,height=760')}catch(error){message($('connectionStatus'),error.message,'error')}});
$('refreshButton').addEventListener('click',()=>loadOptions().catch(error=>message($('connectionStatus'),error.message,'error')));
$('logoutButton').addEventListener('click',()=>{sessionStorage.removeItem(tokenKey);location.reload()});
async function publish(){if(!$('consent').checked){message($('operationStatus'),'Confirme a autorização antes de publicar.','warn');return}if(!$('videoOption').value){message($('operationStatus'),'Selecione um vídeo pronto.','warn');return}const selected=JSON.parse($('videoOption').value);if(!confirm('Confirmar a publicação deste Reel no Instagram?'))return;try{message($('operationStatus'),'Enviando e aguardando o Instagram...','warn');const created=await jsonRequest('/distribution/instagram',{method:'POST',headers:auth(),body:JSON.stringify({campaignId:selected.campaignId,mediaAssetId:selected.mediaAssetId,caption:$('caption').value,hashtags:$('hashtags').value.split(',').map(v=>v.trim()).filter(Boolean),cta:$('cta').value})});await poll(created.distribution.id)}catch(error){message($('operationStatus'),error.message,'error')}}
async function poll(id){for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,2000));const data=await jsonRequest('/distribution/'+id,{headers:auth()});const item=data.distribution;if(item.status==='published'){message($('operationStatus'),'Reel publicado com sucesso no Instagram.','ok');return}if(item.status==='failed'){throw new Error(item.lastError||'O Instagram recusou a publicação.')}}throw new Error('O Instagram ainda está processando. Consulte novamente em instantes.')}
$('publishButton').addEventListener('click',publish);restore();
</script></body></html>`;
}
