export function renderTikTokReviewPage() {
  return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Afiliados Pro | Integração TikTok</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#eef2ff;background:#070b18}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at top,#172554,#070b18 55%)}main{max-width:920px;margin:auto;padding:32px 18px 60px}.brand{display:flex;align-items:center;gap:12px;margin-bottom:24px}.logo{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(135deg,#25f4ee,#fe2c55);font-weight:900;color:#080b14}.card{background:rgba(15,23,42,.92);border:1px solid #334155;border-radius:20px;padding:24px;margin:16px 0;box-shadow:0 20px 50px #0005}h1{margin:0;font-size:28px}h2{font-size:20px}p{color:#cbd5e1;line-height:1.55}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{display:block;font-weight:700;margin:12px 0 7px}input,select,textarea{width:100%;padding:12px 14px;border-radius:12px;border:1px solid #475569;background:#0b1224;color:#fff;font:inherit}textarea{min-height:100px;resize:vertical}button{border:0;border-radius:12px;padding:12px 16px;font-weight:800;font-size:15px;cursor:pointer}.primary{background:#fe2c55;color:white}.secondary{background:#25f4ee;color:#071018}.ghost{background:#273449;color:#fff}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.status{border-radius:12px;padding:12px 14px;background:#111c31;color:#dbeafe}.ok{border-left:4px solid #22c55e}.warn{border-left:4px solid #f59e0b}.error{border-left:4px solid #ef4444}.hidden{display:none}.consent,.setting{display:flex;gap:10px;align-items:flex-start;margin-top:12px}.consent input,.setting input{width:auto;margin-top:4px}.settings{margin-top:16px;padding:16px;border:1px solid #334155;border-radius:14px;background:#0b1224}.settings h3{margin:0 0 8px}.note{font-size:13px;color:#94a3b8}@media(max-width:650px){.grid{grid-template-columns:1fr}.card{padding:18px}}
</style></head><body><main>
<div class="brand"><div class="logo">AP</div><div><h1>Afiliados Pro</h1><p style="margin:2px 0">Integração oficial com TikTok</p></div></div>
<section id="loginCard" class="card"><h2>Entrar</h2><p>Use sua conta Afiliados Pro para gerenciar somente suas próprias campanhas e conexões.</p>
<form id="loginForm"><label for="email">E-mail</label><input id="email" type="email" autocomplete="username" required><label for="password">Senha</label><input id="password" type="password" autocomplete="current-password" required><div class="actions"><button class="primary" type="submit">Entrar com segurança</button></div></form><div id="loginStatus"></div></section>
<section id="appCard" class="card hidden"><h2>Conta TikTok</h2><div id="connectionStatus" class="status warn">Verificando conexão...</div><div class="actions"><button id="connectButton" class="secondary" type="button">Conectar TikTok</button><button id="refreshButton" class="ghost" type="button">Atualizar status</button><button id="logoutButton" class="ghost" type="button">Sair</button></div></section>
<section id="publishCard" class="card hidden"><h2>Enviar vídeo ao TikTok</h2><p>Selecione um vídeo pronto da sua campanha. Você decide entre receber um rascunho para editar no TikTok ou publicar diretamente.</p>
<label for="videoOption">Campanha e vídeo</label><select id="videoOption"></select>
<div class="grid"><div><label for="caption">Legenda</label><textarea id="caption" maxlength="1800">Oferta selecionada pelo Afiliados Pro. Confira esta oportunidade.</textarea></div><div><label for="hashtags">Hashtags</label><input id="hashtags" value="oferta, afiliadospro"><label for="cta">Chamada para ação</label><input id="cta" value="Confira a oferta"></div></div>
<div id="creatorSettings" class="settings"><h3>Opções atuais da conta TikTok</h3><label for="privacyLevel">Quem pode assistir</label><select id="privacyLevel"><option value="SELF_ONLY">Somente eu</option></select><label class="setting"><input id="allowComment" type="checkbox"><span>Permitir comentários</span></label><label class="setting"><input id="allowDuet" type="checkbox"><span>Permitir Dueto</span></label><label class="setting"><input id="allowStitch" type="checkbox"><span>Permitir Costura</span></label><label class="setting"><input type="checkbox" checked disabled><span>Divulgar como parceria paga (conteúdo de afiliado)</span></label></div>
<label class="consent"><input id="consent" type="checkbox"><span>Eu revisei este conteúdo e autorizo o Afiliados Pro a enviá-lo para a minha conta TikTok.</span></label>
<div class="actions"><button id="draftButton" class="secondary" type="button">Enviar como rascunho</button><button id="directButton" class="primary" type="button">Publicar no TikTok</button></div>
<p class="note">No ambiente Sandbox, a publicação direta é privada. O rascunho exige que você abra a notificação do TikTok para revisar e concluir.</p><div id="operationStatus"></div></section>
</main><script>
const tokenKey='afiliadosProReviewToken';const $=(id)=>document.getElementById(id);let token=sessionStorage.getItem(tokenKey)||'';
function auth(){return {'Authorization':'Bearer '+token,'Content-Type':'application/json'}}
function message(target,text,type='warn'){target.className='status '+type;target.textContent=String(text)}
async function jsonRequest(url,options={}){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Não foi possível concluir a operação.');return data}
async function loadCreatorInfo(){const data=await jsonRequest('/channel/tiktok/creator-info',{headers:auth()});const creator=data.creator;const labels={PUBLIC_TO_EVERYONE:'Todos',MUTUAL_FOLLOW_FRIENDS:'Amigos que se seguem',FOLLOWER_OF_CREATOR:'Seguidores',SELF_ONLY:'Somente eu'};const select=$('privacyLevel');select.innerHTML='';creator.privacyLevelOptions.forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=labels[value]||value;select.appendChild(option)});if(creator.privacyLevelOptions.includes('SELF_ONLY'))select.value='SELF_ONLY';[['allowComment','commentDisabled'],['allowDuet','duetDisabled'],['allowStitch','stitchDisabled']].forEach(([id,key])=>{const input=$(id);input.checked=!creator[key];input.disabled=creator[key]})}
async function loadOptions(){const data=await jsonRequest('/distribution/tiktok/options',{headers:auth()});$('appCard').classList.remove('hidden');if(data.connected){message($('connectionStatus'),'Conectado: '+data.connection.destinationName,'ok');$('publishCard').classList.remove('hidden');await loadCreatorInfo()}else{message($('connectionStatus'),'Nenhuma conta TikTok conectada.','warn');$('publishCard').classList.add('hidden')}
const select=$('videoOption');select.innerHTML='';data.options.forEach(item=>{const option=document.createElement('option');option.value=JSON.stringify(item);option.textContent=item.campaignName+' — vídeo pronto';select.appendChild(option)});if(!data.options.length){const option=document.createElement('option');option.textContent='Nenhum vídeo pronto encontrado';option.value='';select.appendChild(option)}}
async function restore(){if(!token)return;$('loginCard').classList.add('hidden');try{await loadOptions()}catch(error){token='';sessionStorage.removeItem(tokenKey);$('loginCard').classList.remove('hidden');message($('loginStatus'),error.message,'error')}}
$('loginForm').addEventListener('submit',async(event)=>{event.preventDefault();try{const data=await jsonRequest('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});token=data.token;sessionStorage.setItem(tokenKey,token);$('password').value='';$('loginCard').classList.add('hidden');await loadOptions()}catch(error){message($('loginStatus'),error.message,'error')}});
$('connectButton').addEventListener('click',async()=>{try{const data=await jsonRequest('/channel/tiktok/oauth/start',{headers:auth()});window.open(data.authorizationUrl,'tiktokOAuth','width=760,height=760')}catch(error){message($('connectionStatus'),error.message,'error')}});
$('refreshButton').addEventListener('click',()=>loadOptions().catch(error=>message($('connectionStatus'),error.message,'error')));
$('logoutButton').addEventListener('click',()=>{sessionStorage.removeItem(tokenKey);location.reload()});
async function send(mode){if(!$('consent').checked){message($('operationStatus'),'Confirme a autorização antes de enviar.','warn');return}if(!$('videoOption').value){message($('operationStatus'),'Selecione um vídeo pronto.','warn');return}const selected=JSON.parse($('videoOption').value);const endpoint=mode==='draft'?'/distribution/tiktok/draft':'/distribution/tiktok';const label=mode==='draft'?'rascunho':'publicação no TikTok';if(!confirm('Confirmar o envio como '+label+'?'))return;try{message($('operationStatus'),'Enviando e aguardando o TikTok...','warn');const created=await jsonRequest(endpoint,{method:'POST',headers:auth(),body:JSON.stringify({campaignId:selected.campaignId,mediaAssetId:selected.mediaAssetId,caption:$('caption').value,hashtags:$('hashtags').value.split(',').map(v=>v.trim()).filter(Boolean),cta:$('cta').value,privacyLevel:$('privacyLevel').value,disableComment:!$('allowComment').checked,disableDuet:!$('allowDuet').checked,disableStitch:!$('allowStitch').checked})});await poll(created.distribution.id,mode)}catch(error){message($('operationStatus'),error.message,'error')}}
async function poll(id,mode){for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,2000));const data=await jsonRequest('/distribution/'+id,{headers:auth()});const item=data.distribution;if(item.status==='delivered'){message($('operationStatus'),'Rascunho entregue. Abra a caixa de entrada do TikTok para revisar e publicar.','ok');return}if(item.status==='published'){message($('operationStatus'),'Publicação privada confirmada pelo TikTok.','ok');return}if(item.status==='failed'){throw new Error(item.lastError||'O TikTok recusou o envio.')}}throw new Error('O TikTok ainda está processando. Consulte novamente em instantes.')}
$('draftButton').addEventListener('click',()=>send('draft'));$('directButton').addEventListener('click',()=>send('direct'));restore();
</script></body></html>`;
}
