name: Deploy SaaS to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t saas-api .

      - name: Tag image
        run: docker tag saas-api:latest ${{ secrets.DOCKER_USERNAME }}/saas-api:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/saas-api:latest

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name saas-cluster --region us-east-1
          kubectl apply -f k8s/